# This rule is not used by the project samba-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over samba-operator.samba.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: samba-operator
    app.kubernetes.io/managed-by: kustomize
  name: smbsecurityconfig-admin-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbsecurityconfigs
    verbs:
      - '*'
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbsecurityconfigs/status
    verbs:
      - get
