# This rule is not used by the project samba-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the samba-operator.samba.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: samba-operator
    app.kubernetes.io/managed-by: kustomize
  name: smbshare-editor-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares/status
    verbs:
      - get
