# This rule is not used by the project samba-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to samba-operator.samba.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: samba-operator
    app.kubernetes.io/managed-by: kustomize
  name: smbshare-viewer-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares/status
    verbs:
      - get
